"use client";
import { useCallback, useEffect, useState } from "react";
import PeriodSelector from "@/components/kpi/PeriodSelector";
import { exportTerritoryProductRanking, getErrorMessage, getTerritoryKpiTeam, getTerritoryProductRanking } from "@/lib/api";
import { formatMoney } from "@/lib/importLabels";
import { PeriodKey, TerritoryProductRankingResponse } from "@/lib/types";
import { useAuthStore } from "@/store/useAuthStore";
function defaultPeriod(): PeriodKey { const now=new Date(); return { periodType:"MONTH",year:now.getFullYear(),periodNumber:now.getMonth()+1 }; }
const statusLabel={ NEVER_SOLD_IN_TERRITORY:"ยังไม่เคยขายในเขตนี้เลย", SOLD_BEFORE_NOT_IN_PERIOD:"เคยขายได้ แต่ไม่มีในงวดที่เลือก" };
export default function TerritoryProductsPage(){const token=useAuthStore(s=>s.token);const [period,setPeriod]=useState<PeriodKey>(defaultPeriod());const [territories,setTerritories]=useState<{id:string;name:string}[]>([]);const [territoryId,setTerritoryId]=useState("");const [data,setData]=useState<TerritoryProductRankingResponse|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(false);useEffect(()=>{if(!token)return;void getTerritoryKpiTeam(token,period).then(r=>{const entries=r.territories.map(x=>({id:x.territoryId,name:x.name}));setTerritories(entries);setTerritoryId(value=>value||entries[0]?.id||"");}).catch(e=>setError(getErrorMessage(e,"โหลดรายชื่อเขตไม่สำเร็จ")));},[period,token]);const load=useCallback(async()=>{if(!token||!territoryId)return;setLoading(true);try{setData(await getTerritoryProductRanking(token,territoryId,period));setError(null);}catch(e){setData(null);setError(getErrorMessage(e,"โหลดอันดับสินค้าไม่สำเร็จ"));}finally{setLoading(false);}},[period,territoryId,token]);useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
void load();},[load]);async function exportFile(){if(!token||!territoryId)return;try{await exportTerritoryProductRanking(token,territoryId,period);}catch(e){setError(getErrorMessage(e,"ส่งออกอันดับสินค้าไม่สำเร็จ"));}}return <div className="mx-auto max-w-7xl p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold text-zinc-900">อันดับสินค้ารายเขต</h1><p className="mt-1 text-sm text-zinc-600">เรียงตามยอดขายของเขตในงวดที่เลือก</p></div><button type="button" onClick={()=>void exportFile()} disabled={!territoryId} className="rounded border border-zinc-300 px-3 py-2 text-sm font-medium text-zinc-700 disabled:opacity-50">Export Excel</button></div><div className="mt-4 flex flex-wrap items-center gap-3"><label className="text-sm font-medium text-zinc-600">เขต <select value={territoryId} onChange={e=>setTerritoryId(e.target.value)} className="ml-2 rounded border border-zinc-300 px-3 py-2">{territories.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><PeriodSelector value={period} onChange={setPeriod}/></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}{loading&&<p className="mt-6 text-zinc-400">กำลังโหลด...</p>}{data&&!loading&&<div className="mt-6 space-y-4"><p className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">{data.zeroSaleWarning}</p><div className="overflow-x-auto rounded-lg border border-zinc-200 bg-white"><table className="min-w-full divide-y divide-zinc-200 text-sm"><thead className="bg-zinc-50 text-left text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-3 py-2">รหัส</th><th className="px-3 py-2">สินค้า</th><th className="px-3 py-2">กลุ่มสินค้า</th><th className="px-3 py-2 text-right">ยอดขาย</th><th className="px-3 py-2 text-right">จำนวน</th><th className="px-3 py-2">สถานะ</th></tr></thead><tbody className="divide-y divide-zinc-100">{data.items.map(i=><tr key={i.productId}><td title={i.code==="—"?"สินค้านี้ยังไม่มีรหัสจากแคตตาล็อก":""} className="px-3 py-2">{i.code}</td><td className="px-3 py-2 font-medium">{i.name}</td><td className="px-3 py-2">{i.productType.name}</td><td className="px-3 py-2 text-right">{formatMoney(i.revenue)}</td><td className="px-3 py-2 text-right">{i.quantity.toLocaleString("th-TH",{maximumFractionDigits:2})}</td><td className="px-3 py-2">{i.zeroSaleStatus&&<span className="rounded-full bg-zinc-100 px-2 py-0.5 text-xs text-zinc-700">{statusLabel[i.zeroSaleStatus]}</span>}</td></tr>)}</tbody></table></div>{data.personalBucket&&<section className="rounded-lg border border-zinc-200 bg-white p-4"><h2 className="font-semibold text-zinc-900">ยอดขายส่วนบุคคล</h2><p className="mt-1 text-sm text-zinc-600">ยอดนี้ไม่ถูกรวมในเขตใด</p><ul className="mt-3 space-y-1 text-sm">{data.personalBucket.map(i=><li key={i.productId}>{i.name}: {formatMoney(i.revenue)}</li>)}</ul></section>}</div>}</div>}
