import { Request, Response } from "express";
import { prisma } from "../lib/prisma";
import * as territoryService from "../services/territory.service";

const notFound = (res: Response, entity: string) => res.status(404).json({ error: `${entity} not found` });
const handle = (res: Response, error: unknown) => { if (error && typeof error === "object" && "status" in error) { const known = error as { status: number; message?: string }; return res.status(Number(known.status)).json({ error: known.message ?? "Request failed" }); } throw error; };

export async function listTerritories(_req: Request, res: Response) { const today = new Date(); const territories = await prisma.territory.findMany({ include: { _count: { select: { assignments: { where: { OR: [{ effectiveTo: null }, { effectiveTo: { gte: today } }] } }, hospitals: true } }, region: { select: { id: true, name: true } } }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); res.json({ territories: territories.map((territory) => ({ ...territory, activeOwnerCount: territory._count.assignments, hospitalCount: territory._count.hospitals })) }); }
export async function createTerritory(req: Request, res: Response) { const { regionId, ...body } = req.body; if (regionId && !await prisma.region.findUnique({ where: { id: regionId } })) return notFound(res, "Region"); const territory = await prisma.territory.create({ data: { ...body, regionId: regionId ?? null } }); res.status(201).json({ territory }); }
export async function updateTerritory(req: Request, res: Response) { const { id } = req.params; const { regionId, ...body } = req.body; if (!await prisma.territory.findUnique({ where: { id } })) return notFound(res, "Territory"); if (regionId && !await prisma.region.findUnique({ where: { id: regionId } })) return notFound(res, "Region"); const territory = await prisma.territory.update({ where: { id }, data: { ...body, ...(regionId !== undefined ? { regionId } : {}) } }); res.json({ territory }); }
export async function listAssignments(req: Request, res: Response) { const { territoryId, salespersonId, status } = req.query as { territoryId?: string; salespersonId?: string; status?: "ACTIVE" | "INACTIVE" }; const today = new Date(); const where = { ...(territoryId ? { territoryId } : {}), ...(salespersonId ? { salespersonId } : {}), ...(status === "ACTIVE" ? { OR: [{ effectiveTo: null }, { effectiveTo: { gte: today } }] } : status === "INACTIVE" ? { effectiveTo: { lt: today } } : {}) }; const assignments = await prisma.territoryAssignment.findMany({ where, include: { territory: true, salesperson: { select: { id: true, displayName: true } }, assignedBy: { select: { id: true, displayName: true } } }, orderBy: { effectiveFrom: "desc" } }); res.json({ territoryAssignments: assignments }); }
export async function putAssignment(req: Request, res: Response) { const { territoryId, salespersonId, effectiveTo } = req.body; if (!await prisma.territory.findUnique({ where: { id: territoryId } })) return notFound(res, "Territory"); if (!await prisma.salesperson.findUnique({ where: { id: salespersonId } })) return notFound(res, "Salesperson"); try { if (effectiveTo != null) { const closed = await territoryService.withdrawAssignment({ territoryId, salespersonId, effectiveTo }); if (!closed) return notFound(res, "Territory assignment"); return res.json({ assignment: closed }); } const created = await territoryService.assignTerritory(req.body, req.user!.id); res.status(201).json({ assignment: created }); } catch (error) { return handle(res, error); } }
export async function patchHospitalTerritory(req: Request, res: Response) { const { id } = req.params; const { territoryId, note } = req.body; const hospital = await prisma.hospital.findUnique({ where: { id } }); if (!hospital) return notFound(res, "Hospital"); if (territoryId && !await prisma.territory.findUnique({ where: { id: territoryId } })) return notFound(res, "Territory"); const updated = await prisma.$transaction(async (tx) => { const result = await tx.hospital.update({ where: { id }, data: { territoryId, territorySource: "MANUAL" } }); await tx.hospitalTerritoryChange.create({ data: { hospitalId: id, fromTerritoryId: hospital.territoryId, toTerritoryId: territoryId, changedById: req.user!.id, note: note ?? null } }); return result; }); res.json({ hospital: updated }); }
export async function bulkByProvince(req: Request, res: Response) { const { province, territoryId, note } = req.body; if (!await prisma.territory.findUnique({ where: { id: territoryId } })) return notFound(res, "Territory"); const hospitals = await prisma.hospital.findMany({ where: { province }, select: { id: true, territoryId: true } }); await prisma.$transaction(async (tx) => { for (const hospital of hospitals) { await tx.hospital.update({ where: { id: hospital.id }, data: { territoryId, territorySource: "MANUAL" } }); await tx.hospitalTerritoryChange.create({ data: { hospitalId: hospital.id, fromTerritoryId: hospital.territoryId, toTerritoryId: territoryId, changedById: req.user!.id, note: note ?? null } }); } }); res.json({ updatedCount: hospitals.length }); }
export async function unassignedHospitals(_req: Request, res: Response) { res.json(await territoryService.listUnassignedTerritoryHospitals()); }
export async function derivedTarget(req: Request, res: Response) { const { salespersonId, year, month } = req.params as unknown as { salespersonId: string; year: number; month: number }; if (!await prisma.salesperson.findUnique({ where: { id: salespersonId } })) return notFound(res, "Salesperson"); res.json({ derivedTarget: await territoryService.getDerivedTarget(salespersonId, year, month) }); }
export async function upsertTerritoryTarget(req: Request, res: Response) { const { territoryId, year, month } = req.params as unknown as { territoryId: string; year: number; month: number }; if (!await prisma.territory.findUnique({ where: { id: territoryId } })) return notFound(res, "Territory"); try { const target = await territoryService.upsertScopedTarget("TERRITORY", territoryId, year, month, req.body, req.user!.id); res.json({ target }); } catch (error) { return handle(res, error); } }
export async function listGroups(_req: Request, res: Response) { const territoryGroups = await prisma.territoryGroup.findMany({ include: { members: { include: { territory: true }, orderBy: { effectiveFrom: "desc" } } }, orderBy: { name: "asc" } }); res.json({ territoryGroups }); }
export async function createGroup(req: Request, res: Response) { const group = await prisma.territoryGroup.create({ data: req.body }); res.status(201).json({ group }); }
export async function updateGroup(req: Request, res: Response) { const { id } = req.params; if (!await prisma.territoryGroup.findUnique({ where: { id } })) return notFound(res, "Territory group"); const group = await prisma.territoryGroup.update({ where: { id }, data: req.body }); res.json({ group }); }
export async function addGroupMember(req: Request, res: Response) { const { id } = req.params; const { territoryId, effectiveFrom, effectiveTo } = req.body; if (!await prisma.territory.findUnique({ where: { id: territoryId } })) return notFound(res, "Territory"); try { const member = await territoryService.addGroupMember(id, territoryId, { effectiveFrom, effectiveTo: effectiveTo ?? null }); if (!member) return notFound(res, "Territory group"); res.status(201).json({ member }); } catch (error) { return handle(res, error); } }
export async function updateGroupMember(req: Request, res: Response) { const { id, memberId } = req.params; const { effectiveFrom, effectiveTo } = req.body; try { const member = await territoryService.updateGroupMember(id, memberId, { effectiveFrom, effectiveTo }); if (!member) return notFound(res, "Territory group member"); res.json({ member }); } catch (error) { return handle(res, error); } }
export async function upsertGroupTarget(req: Request, res: Response) { const { territoryGroupId, year, month } = req.params as unknown as { territoryGroupId: string; year: number; month: number }; if (!await prisma.territoryGroup.findUnique({ where: { id: territoryGroupId } })) return notFound(res, "Territory group"); const target = await territoryService.upsertScopedTarget("TERRITORY_GROUP", territoryGroupId, year, month, req.body, req.user!.id); res.json({ target }); }
