import { Request, Response } from "express";
import { prisma } from "../lib/prisma";
import { PeriodQuery } from "../validators/kpi.validators";
import { computeTerritoryKpi, getTerritoryBuckets, TERRITORY_RANK_ONLY_FIELDS } from "../services/territoryKpi.service";
import { resolveViewerTerritoryIds } from "../services/viewerTerritoryScope.service";

export async function serializeTerritoryKpiRow(req: Request, period: PeriodQuery, territory: { id: string; name: string }) {
  const result = await computeTerritoryKpi(territory.id, period);
  const owners = await prisma.territoryAssignment.findMany({ where: { territoryId: territory.id, effectiveFrom: { lte: new Date(Date.UTC(period.year, (period.periodType === "MONTH" ? period.periodNumber : period.periodType === "QUARTER" ? period.periodNumber * 3 : 12) - 1, 1)) }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: new Date(Date.UTC(period.year, 0, 1)) } }] }, include: { salesperson: { select: { displayName: true } } } });
  const row = { territoryId: territory.id, name: territory.name, ownerNames: owners.map((owner) => owner.salesperson.displayName), revenue: result.revenue, target: result.target, achievementPercent: result.achievementPercent, compositeScore: result.composite, computedMetricLabel: result.computedFromLabel, metrics: result.metrics };
  const permitted = await resolveViewerTerritoryIds(req.user!.id, req.user!.role, period);
  if (permitted === null || permitted.has(territory.id)) return { ...row, visibility: "TERRITORY_FULL" };
  const restricted = Object.fromEntries(TERRITORY_RANK_ONLY_FIELDS.filter((field) => field !== "rank").map((field) => [field, row[field]]));
  return { ...restricted, visibility: "TERRITORY_RANK_ONLY" } as { territoryId: string; name: string; ownerNames: string[]; compositeScore: number | null; computedMetricLabel: string; visibility: string };
}
export async function getTerritoryKpi(req: Request, res: Response) { const territory = await prisma.territory.findUnique({ where: { id: req.params.territoryId } }); if (!territory) return res.status(404).json({ error: "Territory not found" }); res.json({ period: req.query, territory: await serializeTerritoryKpiRow(req, req.query as unknown as PeriodQuery, territory) }); }
export async function getTeamTerritoryKpi(req: Request, res: Response) { const period = req.query as unknown as PeriodQuery; const territories = await prisma.territory.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } }); const rows = await Promise.all(territories.map((territory) => serializeTerritoryKpiRow(req, period, territory))); const ranked = [...rows].sort((a, b) => (b.compositeScore ?? -1) - (a.compositeScore ?? -1)).map((row, index) => ({ ...row, rank: index + 1 })); const buckets = req.user!.role === "MANAGER" ? await getTerritoryBuckets(period) : undefined; res.json({ period, territories: ranked, ...(buckets ? { buckets } : {}) }); }
export async function territoryDrillDown(req: Request, res: Response) { const territory = await prisma.territory.findUnique({ where: { id: req.params.territoryId } }); if (!territory) return res.status(404).json({ error: "Territory not found" }); const permitted = await resolveViewerTerritoryIds(req.user!.id, req.user!.role, req.query as unknown as PeriodQuery); if (permitted !== null && !permitted.has(territory.id)) return res.status(403).json({ error: "Forbidden" }); const period = req.query as unknown as PeriodQuery; const months = period.periodType === "MONTH" ? [{ year: period.year, month: period.periodNumber }] : period.periodType === "QUARTER" ? [0,1,2].map((offset) => ({ year: period.year, month: (period.periodNumber - 1) * 3 + offset + 1 })) : Array.from({ length: 12 }, (_, i) => ({ year: period.year, month: i + 1 })); const credits = await prisma.salesLineCredit.findMany({ where: { salesperson: { excludedFromTerritoryTotals: false }, salesLine: { hospital: { territoryId: territory.id }, OR: months } }, select: { sharePercent: true, salesLine: { select: { total: true, hospital: { select: { id: true, displayName: true } }, productType: { select: { id: true, name: true } } } } } }); const totals = new Map<string, { id: string; name: string; revenue: number }>(); const hospitals = new Map<string, { id: string; name: string; revenue: number }>(); for (const credit of credits) { const revenue = Number(credit.salesLine.total) * Number(credit.sharePercent) / 100; const type = credit.salesLine.productType; const hospital = credit.salesLine.hospital; totals.set(type.id, { id: type.id, name: type.name, revenue: (totals.get(type.id)?.revenue ?? 0) + revenue }); hospitals.set(hospital.id, { id: hospital.id, name: hospital.displayName, revenue: (hospitals.get(hospital.id)?.revenue ?? 0) + revenue }); } res.json({ territory: { id: territory.id, name: territory.name }, metric: req.params.metric, productTypes: [...totals.values()].sort((a,b) => b.revenue-a.revenue), hospitals: [...hospitals.values()].sort((a,b) => b.revenue-a.revenue) }); }
