import ExcelJS from "exceljs";
import { Request, Response } from "express";
import { prisma } from "../lib/prisma";
import { PeriodQuery } from "../validators/kpi.validators";
import { getTerritoryBuckets } from "../services/territoryKpi.service";
import { serializeTerritoryKpiRow } from "./territoryKpi.controller";
import { monthsInPeriod } from "../services/period.util";
import { resolveViewerTerritoryIds } from "../services/viewerTerritoryScope.service";

async function overview(req: Request, period: PeriodQuery) {
  const territories = await prisma.territory.findMany({ where: { isActive: true }, orderBy: { sortOrder: "asc" } });
  const rows = await Promise.all(territories.map((territory) => serializeTerritoryKpiRow(req, period, territory)));
  const ranked = [...rows].sort((a, b) => (b.compositeScore ?? -1) - (a.compositeScore ?? -1)).map((row, index) => ({ ...row, rank: index + 1 }));
  const months = monthsInPeriod(period); const start = new Date(Date.UTC(months[0].year, months[0].month - 1, 1)); const endMonth = months[months.length - 1]; const end = new Date(Date.UTC(endMonth.year, endMonth.month, 0));
  const groups = await prisma.territoryGroup.findMany({ where: { isActive: true, members: { some: { effectiveFrom: { lte: end }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: start } }] } } }, include: { members: { where: { effectiveFrom: { lte: end }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: start } }] }, include: { territory: true } } } });
  const visibleTerritoryIds = await resolveViewerTerritoryIds(req.user!.id, req.user!.role, period);
  const rawGroups = await Promise.all(groups.map(async (group) => { const memberTerritoryIds = group.members.map((member) => member.territoryId); const memberRows = ranked.filter((row) => memberTerritoryIds.includes(row.territoryId)); const target = await prisma.target.aggregate({ where: { scope: "TERRITORY_GROUP", territoryGroupId: group.id, OR: months.map((month) => ({ year: month.year, month: month.month })) }, _sum: { revenueTarget: true } }); const revenue = memberRows.reduce((sum, row) => sum + ((row as { revenue?: number }).revenue ?? 0), 0); const revenueTarget = Number(target._sum.revenueTarget ?? 0); const ownerRows = await prisma.territoryAssignment.findMany({ where: { territoryId: { in: memberTerritoryIds }, effectiveFrom: { lte: new Date() }, OR: [{ effectiveTo: null }, { effectiveTo: { gte: new Date() } }] }, select: { salesperson: { select: { displayName: true } } } }); const ownerNames = [...new Set(ownerRows.map((row) => row.salesperson.displayName))]; const achievementPercent = revenueTarget ? revenue / revenueTarget * 100 : null; return { territoryId: group.id, name: group.name, ownerNames: ownerNames.length ? ownerNames : ["ยังไม่มีผู้ดูแล"], memberTerritoryIds, revenue, revenueTarget, achievementPercent, compositeScore: achievementPercent === null ? null : Math.min(achievementPercent, 100), computedMetricLabel: "คิดจาก 1 จาก 5 เกณฑ์" }; }));
  const rankedGroups = [...rawGroups].sort((a, b) => (b.compositeScore ?? -1) - (a.compositeScore ?? -1)).map((group, index) => ({ ...group, rank: index + 1 }));
  const territoryGroups = rankedGroups.map((group) => { const full = visibleTerritoryIds === null || group.memberTerritoryIds.some((id) => visibleTerritoryIds.has(id)); if (full) return { ...group, visibility: "TERRITORY_FULL" }; return { territoryId: group.territoryId, name: group.name, ownerNames: group.ownerNames, rank: group.rank, compositeScore: group.compositeScore, computedMetricLabel: group.computedMetricLabel, visibility: "TERRITORY_RANK_ONLY" }; });
  return { period, territories: ranked, territoryGroups, ...(req.user!.role === "MANAGER" ? { buckets: await getTerritoryBuckets(period) } : {}) };
}
export async function getTerritoryOverview(req: Request, res: Response) { res.json(await overview(req, req.query as unknown as PeriodQuery)); }
export async function exportTerritoryOverview(req: Request, res: Response) { const data = await overview(req, req.query as unknown as PeriodQuery); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet("Territory overview"); sheet.columns = [{ header: "เขต/กลุ่มเขต", key: "name", width: 28 }, { header: "ผู้ดูแล", key: "owners", width: 30 }, { header: "อันดับ", key: "rank", width: 10 }, { header: "คะแนนรวม", key: "score", width: 15 }, { header: "คิดจาก", key: "label", width: 24 }, { header: "ยอดขาย", key: "revenue", width: 16 }, { header: "เป้า", key: "target", width: 16 }, { header: "% ถึงเป้า", key: "achievement", width: 15 }]; for (const row of [...data.territories, ...data.territoryGroups]) { const full = row as typeof row & { revenue?: number; target?: number; revenueTarget?: number; achievementPercent?: number | null }; sheet.addRow({ name: row.name, owners: row.ownerNames.join(", "), rank: row.rank, score: row.compositeScore, label: row.computedMetricLabel, ...(row.visibility === "TERRITORY_FULL" ? { revenue: full.revenue, target: full.target ?? full.revenueTarget, achievement: full.achievementPercent } : {}) }); } res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); res.setHeader("Content-Disposition", "attachment; filename=territory-overview.xlsx"); await workbook.xlsx.write(res); res.end(); }
