import { Router } from "express";
import { authenticate, requirePasswordChanged } from "../middleware/authenticate";
import { validate } from "../middleware/validate";
import { asyncHandler } from "../utils/asyncHandler";
import * as c from "../controllers/territoryKpi.controller";
import { periodQuerySchema } from "../validators/kpi.validators";
import { z } from "zod";
const router = Router(); const territoryId = z.object({ territoryId: z.string().min(1) }); const drill = z.object({ territoryId: z.string().min(1), metric: z.enum(["REVENUE_VS_TARGET", "NEW_CUSTOMERS", "PRODUCT_GROUP", "RETENTION", "CONSISTENCY"]) });
router.use(authenticate, requirePasswordChanged);
router.get("/team", validate(periodQuerySchema, "query"), asyncHandler(c.getTeamTerritoryKpi));
router.get("/:territoryId/drill-down/:metric", validate(drill, "params"), validate(periodQuerySchema, "query"), asyncHandler(c.territoryDrillDown));
router.get("/:territoryId", validate(territoryId, "params"), validate(periodQuerySchema, "query"), asyncHandler(c.getTerritoryKpi));
export default router;
